//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CasinoReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Karta", Namespace="http://schemas.datacontract.org/2004/07/CasinoService")]
    [System.SerializableAttribute()]
    public partial class Karta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BojaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrojField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Boja {
            get {
                return this.BojaField;
            }
            set {
                if ((object.ReferenceEquals(this.BojaField, value) != true)) {
                    this.BojaField = value;
                    this.RaisePropertyChanged("Boja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Broj {
            get {
                return this.BrojField;
            }
            set {
                if ((this.BrojField.Equals(value) != true)) {
                    this.BrojField = value;
                    this.RaisePropertyChanged("Broj");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CasinoReference.ICasino")]
    public interface ICasino {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasino/DijeliKartu", ReplyAction="http://tempuri.org/ICasino/DijeliKartuResponse")]
        Client.CasinoReference.Karta DijeliKartu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasino/DijeliKartu", ReplyAction="http://tempuri.org/ICasino/DijeliKartuResponse")]
        System.Threading.Tasks.Task<Client.CasinoReference.Karta> DijeliKartuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasino/BacamKartu", ReplyAction="http://tempuri.org/ICasino/BacamKartuResponse")]
        bool BacamKartu(Client.CasinoReference.Karta karta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasino/BacamKartu", ReplyAction="http://tempuri.org/ICasino/BacamKartuResponse")]
        System.Threading.Tasks.Task<bool> BacamKartuAsync(Client.CasinoReference.Karta karta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasino/SveBaceneKarte", ReplyAction="http://tempuri.org/ICasino/SveBaceneKarteResponse")]
        Client.CasinoReference.Karta[] SveBaceneKarte();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICasino/SveBaceneKarte", ReplyAction="http://tempuri.org/ICasino/SveBaceneKarteResponse")]
        System.Threading.Tasks.Task<Client.CasinoReference.Karta[]> SveBaceneKarteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICasinoChannel : Client.CasinoReference.ICasino, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CasinoClient : System.ServiceModel.ClientBase<Client.CasinoReference.ICasino>, Client.CasinoReference.ICasino {
        
        public CasinoClient() {
        }
        
        public CasinoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CasinoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasinoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CasinoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.CasinoReference.Karta DijeliKartu() {
            return base.Channel.DijeliKartu();
        }
        
        public System.Threading.Tasks.Task<Client.CasinoReference.Karta> DijeliKartuAsync() {
            return base.Channel.DijeliKartuAsync();
        }
        
        public bool BacamKartu(Client.CasinoReference.Karta karta) {
            return base.Channel.BacamKartu(karta);
        }
        
        public System.Threading.Tasks.Task<bool> BacamKartuAsync(Client.CasinoReference.Karta karta) {
            return base.Channel.BacamKartuAsync(karta);
        }
        
        public Client.CasinoReference.Karta[] SveBaceneKarte() {
            return base.Channel.SveBaceneKarte();
        }
        
        public System.Threading.Tasks.Task<Client.CasinoReference.Karta[]> SveBaceneKarteAsync() {
            return base.Channel.SveBaceneKarteAsync();
        }
    }
}
